export const data = [
    // Outubro
    {
        id: 1,
        type: "saida",
        name: "Aluguel",
        category: "Moradia",
        value: 1400,
        month: "Outubro",
    },
    {
        id: 2,
        type: "entrada",
        name: "Salario",
        category: "Renda",
        value: 12467.89,
        month: "Outubro",
    },
    {
        id: 3,
        type: "entrada",
        name: "Investimentos",
        category: "Renda",
        value: 589.76,
        month: "Outubro",
    },
    {
        id: 4,
        type: "saida",
        name: "Condominio",
        category: "Moradia",
        value: 200,
        month: "Outubro",
    },
    {
        id: 5,
        type: "saida",
        name: "Energia",
        category: "Moradia",
        value: 190,
        month: "Outubro",
    },
    {
        id: 6,
        type: "saida",
        name: "Delivery",
        category: "Lazer",
        value: 345.76,
        month: "Outubro",
    },
    {
        id: 7,
        type: "saida",
        name: "Combustivel",
        category: "Transporte",
        value: 678.43,
        month: "Outubro",
    },

    // Novembro
    {
        id: 8,
        type: "saida",
        name: "Supermercado",
        category: "Alimentacao",
        value: 450.50,
        month: "Novembro",
    },
    {
        id: 9,
        type: "saida",
        name: "Academia",
        category: "Saude",
        value: 120,
        month: "Novembro",
    },
    {
        id: 10,
        type: "saida",
        name: "Netflix",
        category: "Lazer",
        value: 39.90,
        month: "Novembro",
    },
    {
        id: 11,
        type: "saida",
        name: "Presente de Aniversário",
        category: "Presentes",
        value: 150,
        month: "Novembro",
    },
    {
        id: 12,
        type: "saida",
        name: "Uber",
        category: "Transporte",
        value: 85.60,
        month: "Novembro",
    },
    {
        id: 13,
        type: "entrada",
        name: "Freelance",
        category: "Renda",
        value: 1200,
        month: "Novembro",
    },
    {
        id: 14,
        type: "saida",
        name: "Plano de Saúde",
        category: "Saude",
        value: 350,
        month: "Novembro",
    },

    // Dezembro
    {
        id: 15,
        type: "saida",
        name: "Restaurante",
        category: "Alimentacao",
        value: 230.45,
        month: "Dezembro",
    },
    {
        id: 16,
        type: "saida",
        name: "Cinema",
        category: "Lazer",
        value: 80,
        month: "Dezembro",
    },
    
    {
        id: 19,
        type: "entrada",
        name: "Bônus",
        category: "Presente",
        value: 800,
        month: "Dezembro",
    },
    {
        id: 20,
        type: "saida",
        name: "Internet",
        category: "Moradia",
        value: 99.90,
        month: "Dezembro",
    },

];